enum UseCases {
  None = "None",
  Register = "Register",
  Login = "Login",
  Counter = "Counter",
  Error = "Error",
  RetrieveUser = "RetrieveUser",
  DeleteUser = "DeleteUser",
  UpdateUser = "UpdateUser",
  CreateProject = "CreateProject",
  UpdateProject = "UpdateProject",
  DeleteProject = "DeleteProject",
  RetrieveAllProjects = "RetrieveAllProjects",
  LinkUserToProject = "LinkUserToProject",
  CreateList = "CreateList",
  UpdateList = "UpdateList",
  DeleteList = "DeleteList",
  RetrieveAllProjectLists = "RetrieveAllProjectLists",
  LinkUserToList = "LinkUserToList",
  CreateTask = "CreateTask",
  UpdateTask = "UpdateTask",
  DeleteTask = "DeleteTask",
  RetrieveProjectTasks = "RetrieveProjectTasks",
  LinkUserToTask = "LinkUserToTask",
}

export { UseCases };
